/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as marketPredictSol from "./MarketPredict.sol";
export * as mocks from "./mocks";
export { Greeter__factory } from "./Greeter__factory";
export { MarketPredictV2__factory } from "./MarketPredictV2__factory";
