/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketPredictSol from "./MarketPredict.sol";
export type { marketPredictSol };
export type { Greeter } from "./Greeter";
