/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketPredictSol from "./MarketPredict.sol";
export type { marketPredictSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { Greeter } from "./Greeter";
export type { MP_TimelockController } from "./MP_TimelockController";
export type { MarketPredictV2 } from "./MarketPredictV2";
