/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MarketPredictInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DIVISOR"
      | "CREATOR_RESOLUTION_WINDOW"
      | "DISPUTE_WINDOW"
      | "EMERGENCY_RESOLUTION_WINDOW"
      | "FEE_BPS"
      | "MIN_BET"
      | "MIN_DISPUTE_STAKE"
      | "calculatePotentialWinnings"
      | "canAutoResolve"
      | "cancelMarket"
      | "claimWinnings"
      | "collectedFees"
      | "createManualMarket"
      | "createPriceMarket"
      | "creatorOverride"
      | "disputeResolution"
      | "finalizeMarket"
      | "getContractBalance"
      | "getCurrentOdds"
      | "getCurrentPrice"
      | "getDisputeInfo"
      | "getMarket"
      | "getPosition"
      | "marketCount"
      | "markets"
      | "owner"
      | "positions"
      | "predict"
      | "priceFeeds"
      | "resolveDispute"
      | "resolveMarket"
      | "resolveMarketWithOracle"
      | "setPriceFeed"
      | "transferOwnership"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorOverride"
      | "DisputeResolved"
      | "MarketCancelled"
      | "MarketCreated"
      | "MarketDisputed"
      | "MarketResolved"
      | "PredictionPlaced"
      | "PriceFeedAdded"
      | "RefundClaimed"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DIVISOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATOR_RESOLUTION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_RESOLUTION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_DISPUTE_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePotentialWinnings",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "canAutoResolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createManualMarket",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPriceMarket",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorOverride",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolution",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentOdds",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predict",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "priceFeeds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarketWithOracle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceFeed",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DIVISOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_RESOLUTION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_RESOLUTION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DISPUTE_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePotentialWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canAutoResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createManualMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPriceMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentOdds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "predict", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarketWithOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace CreatorOverrideEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    newOutcome: boolean,
    reason: string
  ];
  export type OutputTuple = [
    marketId: bigint,
    newOutcome: boolean,
    reason: string
  ];
  export interface OutputObject {
    marketId: bigint;
    newOutcome: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    disputeUpheld: boolean,
    finalOutcome: boolean,
    resolver: AddressLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    disputeUpheld: boolean,
    finalOutcome: boolean,
    resolver: string
  ];
  export interface OutputObject {
    marketId: bigint;
    disputeUpheld: boolean;
    finalOutcome: boolean;
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [marketId: BigNumberish, reason: string];
  export type OutputTuple = [marketId: bigint, reason: string];
  export interface OutputObject {
    marketId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    question: string,
    endTime: BigNumberish,
    creator: AddressLike,
    marketType: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    question: string,
    endTime: bigint,
    creator: string,
    marketType: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    question: string;
    endTime: bigint;
    creator: string;
    marketType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketDisputedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    disputer: AddressLike,
    proposedOutcome: boolean,
    reason: string,
    stake: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    disputer: string,
    proposedOutcome: boolean,
    reason: string,
    stake: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    disputer: string;
    proposedOutcome: boolean;
    reason: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    outcome: boolean,
    yesPool: BigNumberish,
    noPool: BigNumberish,
    resolver: AddressLike,
    resolutionMethod: string
  ];
  export type OutputTuple = [
    marketId: bigint,
    outcome: boolean,
    yesPool: bigint,
    noPool: bigint,
    resolver: string,
    resolutionMethod: string
  ];
  export interface OutputObject {
    marketId: bigint;
    outcome: boolean;
    yesPool: bigint;
    noPool: bigint;
    resolver: string;
    resolutionMethod: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionPlacedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    predictedYes: boolean,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    predictedYes: boolean,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    predictedYes: boolean;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceFeedAddedEvent {
  export type InputTuple = [symbol: string, feedAddress: AddressLike];
  export type OutputTuple = [symbol: string, feedAddress: string];
  export interface OutputObject {
    symbol: string;
    feedAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    grossPayout: BigNumberish,
    feeCharged: BigNumberish,
    netPayout: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    grossPayout: bigint,
    feeCharged: bigint,
    netPayout: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    grossPayout: bigint;
    feeCharged: bigint;
    netPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarketPredict extends BaseContract {
  connect(runner?: ContractRunner | null): MarketPredict;
  waitForDeployment(): Promise<this>;

  interface: MarketPredictInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DIVISOR: TypedContractMethod<[], [bigint], "view">;

  CREATOR_RESOLUTION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  EMERGENCY_RESOLUTION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  MIN_DISPUTE_STAKE: TypedContractMethod<[], [bigint], "view">;

  calculatePotentialWinnings: TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean],
    [bigint],
    "view"
  >;

  canAutoResolve: TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [boolean, boolean, string] & {
        canResolve: boolean;
        outcome: boolean;
        reason: string;
      }
    ],
    "view"
  >;

  cancelMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimWinnings: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  collectedFees: TypedContractMethod<[], [bigint], "view">;

  createManualMarket: TypedContractMethod<
    [_question: string, _duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  createPriceMarket: TypedContractMethod<
    [
      _question: string,
      _duration: BigNumberish,
      _symbol: string,
      _targetPrice: BigNumberish,
      _marketType: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  creatorOverride: TypedContractMethod<
    [_marketId: BigNumberish, _newOutcome: boolean, _reason: string],
    [void],
    "nonpayable"
  >;

  disputeResolution: TypedContractMethod<
    [_marketId: BigNumberish, _proposedOutcome: boolean, _reason: string],
    [void],
    "payable"
  >;

  finalizeMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getCurrentOdds: TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean],
    [bigint],
    "view"
  >;

  getCurrentPrice: TypedContractMethod<
    [_symbol: string],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        updatedAt: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  getDisputeInfo: TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [string, bigint, boolean, string, boolean] & {
        disputer: string;
        disputeStake: bigint;
        proposedOutcome: boolean;
        disputeReason: string;
        canStillDispute: boolean;
      }
    ],
    "view"
  >;

  getMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint, string, bigint] & {
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: boolean;
        yesPool: bigint;
        noPool: bigint;
        creator: string;
        marketType: bigint;
      }
    ],
    "view"
  >;

  getPosition: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        yesShares: bigint;
        noShares: bigint;
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        string
      ] & {
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: boolean;
        yesPool: bigint;
        noPool: bigint;
        totalYesShares: bigint;
        totalNoShares: bigint;
        creator: string;
        createdAt: bigint;
        resolvedAt: bigint;
        marketType: bigint;
        priceFeed: string;
        targetPrice: bigint;
        upperPrice: bigint;
        disputer: string;
        disputeStake: bigint;
        proposedOutcome: boolean;
        disputeReason: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        yesShares: bigint;
        noShares: bigint;
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  predict: TypedContractMethod<
    [_marketId: BigNumberish, _predictYes: boolean],
    [void],
    "payable"
  >;

  priceFeeds: TypedContractMethod<[arg0: string], [string], "view">;

  resolveDispute: TypedContractMethod<
    [_marketId: BigNumberish, _disputeUpheld: boolean],
    [void],
    "nonpayable"
  >;

  resolveMarket: TypedContractMethod<
    [_marketId: BigNumberish, _outcome: boolean],
    [void],
    "nonpayable"
  >;

  resolveMarketWithOracle: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPriceFeed: TypedContractMethod<
    [_symbol: string, _feedAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DIVISOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATOR_RESOLUTION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_RESOLUTION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DISPUTE_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePotentialWinnings"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "canAutoResolve"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [boolean, boolean, string] & {
        canResolve: boolean;
        outcome: boolean;
        reason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createManualMarket"
  ): TypedContractMethod<
    [_question: string, _duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPriceMarket"
  ): TypedContractMethod<
    [
      _question: string,
      _duration: BigNumberish,
      _symbol: string,
      _targetPrice: BigNumberish,
      _marketType: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorOverride"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _newOutcome: boolean, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeResolution"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _proposedOutcome: boolean, _reason: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentOdds"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<
    [_symbol: string],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        updatedAt: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDisputeInfo"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [string, bigint, boolean, string, boolean] & {
        disputer: string;
        disputeStake: bigint;
        proposedOutcome: boolean;
        disputeReason: string;
        canStillDispute: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint, string, bigint] & {
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: boolean;
        yesPool: bigint;
        noPool: bigint;
        creator: string;
        marketType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        yesShares: bigint;
        noShares: bigint;
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        string
      ] & {
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: boolean;
        yesPool: bigint;
        noPool: bigint;
        totalYesShares: bigint;
        totalNoShares: bigint;
        creator: string;
        createdAt: bigint;
        resolvedAt: bigint;
        marketType: bigint;
        priceFeed: string;
        targetPrice: bigint;
        upperPrice: bigint;
        disputer: string;
        disputeStake: bigint;
        proposedOutcome: boolean;
        disputeReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        yesShares: bigint;
        noShares: bigint;
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "predict"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _predictYes: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "priceFeeds"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _disputeUpheld: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _outcome: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarketWithOracle"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceFeed"
  ): TypedContractMethod<
    [_symbol: string, _feedAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CreatorOverride"
  ): TypedContractEvent<
    CreatorOverrideEvent.InputTuple,
    CreatorOverrideEvent.OutputTuple,
    CreatorOverrideEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketDisputed"
  ): TypedContractEvent<
    MarketDisputedEvent.InputTuple,
    MarketDisputedEvent.OutputTuple,
    MarketDisputedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionPlaced"
  ): TypedContractEvent<
    PredictionPlacedEvent.InputTuple,
    PredictionPlacedEvent.OutputTuple,
    PredictionPlacedEvent.OutputObject
  >;
  getEvent(
    key: "PriceFeedAdded"
  ): TypedContractEvent<
    PriceFeedAddedEvent.InputTuple,
    PriceFeedAddedEvent.OutputTuple,
    PriceFeedAddedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "CreatorOverride(uint256,bool,string)": TypedContractEvent<
      CreatorOverrideEvent.InputTuple,
      CreatorOverrideEvent.OutputTuple,
      CreatorOverrideEvent.OutputObject
    >;
    CreatorOverride: TypedContractEvent<
      CreatorOverrideEvent.InputTuple,
      CreatorOverrideEvent.OutputTuple,
      CreatorOverrideEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool,bool,address)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "MarketCancelled(uint256,string)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketCreated(uint256,string,uint256,address,uint8)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketDisputed(uint256,address,bool,string,uint256)": TypedContractEvent<
      MarketDisputedEvent.InputTuple,
      MarketDisputedEvent.OutputTuple,
      MarketDisputedEvent.OutputObject
    >;
    MarketDisputed: TypedContractEvent<
      MarketDisputedEvent.InputTuple,
      MarketDisputedEvent.OutputTuple,
      MarketDisputedEvent.OutputObject
    >;

    "MarketResolved(uint256,bool,uint256,uint256,address,string)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "PredictionPlaced(uint256,address,bool,uint256,uint256)": TypedContractEvent<
      PredictionPlacedEvent.InputTuple,
      PredictionPlacedEvent.OutputTuple,
      PredictionPlacedEvent.OutputObject
    >;
    PredictionPlaced: TypedContractEvent<
      PredictionPlacedEvent.InputTuple,
      PredictionPlacedEvent.OutputTuple,
      PredictionPlacedEvent.OutputObject
    >;

    "PriceFeedAdded(string,address)": TypedContractEvent<
      PriceFeedAddedEvent.InputTuple,
      PriceFeedAddedEvent.OutputTuple,
      PriceFeedAddedEvent.OutputObject
    >;
    PriceFeedAdded: TypedContractEvent<
      PriceFeedAddedEvent.InputTuple,
      PriceFeedAddedEvent.OutputTuple,
      PriceFeedAddedEvent.OutputObject
    >;

    "RefundClaimed(uint256,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
