/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MarketPredictInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DIVISOR"
      | "FEE_BPS"
      | "MAX_STRING_LENGTH"
      | "MIN_BET"
      | "avatars"
      | "balances"
      | "calculatePotentialWinnings"
      | "cancelMarket"
      | "claim"
      | "collectedFees"
      | "createMarket"
      | "deposit"
      | "getBalance"
      | "getMarket"
      | "getMarketBasics"
      | "getMarketPools"
      | "getPosition"
      | "getUserPosition"
      | "globalPaused"
      | "hasClaimed"
      | "initialize"
      | "marketCount"
      | "markets"
      | "nextId"
      | "noAmounts"
      | "owner"
      | "predict"
      | "refund"
      | "renounceOwnership"
      | "resolve"
      | "resolveWithOracle"
      | "setAvatar"
      | "setGlobalPause"
      | "setUsername"
      | "transferOwnership"
      | "usernames"
      | "withdraw"
      | "withdrawFees"
      | "yesAmounts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AvatarSet"
      | "Cancelled"
      | "Deposit"
      | "GlobalPaused"
      | "Initialized"
      | "MarketCreated"
      | "OwnershipTransferred"
      | "Predicted"
      | "Refunded"
      | "Resolved"
      | "UsernameSet"
      | "WinningsClaimed"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DIVISOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_STRING_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "avatars",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePotentialWinnings",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketBasics",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPosition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "noAmounts",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predict",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolve",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveWithOracle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setAvatar", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setGlobalPause",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "setUsername", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usernames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yesAmounts",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DIVISOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STRING_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "avatars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePotentialWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketBasics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noAmounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "predict", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveWithOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAvatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usernames", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yesAmounts", data: BytesLike): Result;
}

export namespace AvatarSetEvent {
  export type InputTuple = [user: AddressLike, avatar: string];
  export type OutputTuple = [user: string, avatar: string];
  export interface OutputObject {
    user: string;
    avatar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    question: string,
    endTime: BigNumberish,
    marketType: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    question: string,
    endTime: bigint,
    marketType: bigint
  ];
  export interface OutputObject {
    id: bigint;
    question: string;
    endTime: bigint;
    marketType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictedEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    choice: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    choice: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    choice: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, id: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    id: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolvedEvent {
  export type InputTuple = [id: BigNumberish, outcome: boolean];
  export type OutputTuple = [id: bigint, outcome: boolean];
  export interface OutputObject {
    id: bigint;
    outcome: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsernameSetEvent {
  export type InputTuple = [user: AddressLike, username: string];
  export type OutputTuple = [user: string, username: string];
  export interface OutputObject {
    user: string;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    gross: BigNumberish,
    fee: BigNumberish,
    net: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    gross: bigint,
    fee: bigint,
    net: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    gross: bigint;
    fee: bigint;
    net: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarketPredict extends BaseContract {
  connect(runner?: ContractRunner | null): MarketPredict;
  waitForDeployment(): Promise<this>;

  interface: MarketPredictInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DIVISOR: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_STRING_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  avatars: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  calculatePotentialWinnings: TypedContractMethod<
    [id: BigNumberish, isYes: boolean],
    [bigint],
    "view"
  >;

  cancelMarket: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  claim: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  collectedFees: TypedContractMethod<[], [bigint], "view">;

  createMarket: TypedContractMethod<
    [
      question: string,
      description: string,
      category: string,
      duration: BigNumberish,
      marketType: BigNumberish,
      priceFeed: AddressLike,
      targetPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  getBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getMarket: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint, string, bigint] & {
        question: string;
        closeTime: bigint;
        status: bigint;
        outcome: boolean;
        yesPool: bigint;
        noPool: bigint;
        creator: string;
        marketType: bigint;
      }
    ],
    "view"
  >;

  getMarketBasics: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        question: string;
        description: string;
        category: string;
        endTime: bigint;
        marketType: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getMarketPools: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, boolean, boolean] & {
        yesPool: bigint;
        noPool: bigint;
        resolved: boolean;
        outcome: boolean;
      }
    ],
    "view"
  >;

  getPosition: TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        yesShares: bigint;
        noShares: bigint;
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getUserPosition: TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  globalPaused: TypedContractMethod<[], [boolean], "view">;

  hasClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        question: string;
        description: string;
        category: string;
        yesPool: bigint;
        noPool: bigint;
        endTime: bigint;
        resolved: boolean;
        outcome: boolean;
        marketType: bigint;
        status: bigint;
        creator: string;
        token: string;
        priceFeed: string;
        targetPrice: bigint;
      }
    ],
    "view"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  noAmounts: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  predict: TypedContractMethod<
    [id: BigNumberish, choice: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  refund: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolve: TypedContractMethod<
    [id: BigNumberish, outcome: boolean],
    [void],
    "nonpayable"
  >;

  resolveWithOracle: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAvatar: TypedContractMethod<[avatarUri: string], [void], "nonpayable">;

  setGlobalPause: TypedContractMethod<[pause: boolean], [void], "nonpayable">;

  setUsername: TypedContractMethod<[name: string], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usernames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawFees: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  yesAmounts: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DIVISOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STRING_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "avatars"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePotentialWinnings"
  ): TypedContractMethod<[id: BigNumberish, isYes: boolean], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      description: string,
      category: string,
      duration: BigNumberish,
      marketType: BigNumberish,
      priceFeed: AddressLike,
      targetPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint, string, bigint] & {
        question: string;
        closeTime: bigint;
        status: bigint;
        outcome: boolean;
        yesPool: bigint;
        noPool: bigint;
        creator: string;
        marketType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketBasics"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        question: string;
        description: string;
        category: string;
        endTime: bigint;
        marketType: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketPools"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, boolean, boolean] & {
        yesPool: bigint;
        noPool: bigint;
        resolved: boolean;
        outcome: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        yesShares: bigint;
        noShares: bigint;
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPosition"
  ): TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        question: string;
        description: string;
        category: string;
        yesPool: bigint;
        noPool: bigint;
        endTime: bigint;
        resolved: boolean;
        outcome: boolean;
        marketType: bigint;
        status: bigint;
        creator: string;
        token: string;
        priceFeed: string;
        targetPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "noAmounts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predict"
  ): TypedContractMethod<
    [id: BigNumberish, choice: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveWithOracle"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAvatar"
  ): TypedContractMethod<[avatarUri: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGlobalPause"
  ): TypedContractMethod<[pause: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUsername"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usernames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yesAmounts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AvatarSet"
  ): TypedContractEvent<
    AvatarSetEvent.InputTuple,
    AvatarSetEvent.OutputTuple,
    AvatarSetEvent.OutputObject
  >;
  getEvent(
    key: "Cancelled"
  ): TypedContractEvent<
    CancelledEvent.InputTuple,
    CancelledEvent.OutputTuple,
    CancelledEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "GlobalPaused"
  ): TypedContractEvent<
    GlobalPausedEvent.InputTuple,
    GlobalPausedEvent.OutputTuple,
    GlobalPausedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Predicted"
  ): TypedContractEvent<
    PredictedEvent.InputTuple,
    PredictedEvent.OutputTuple,
    PredictedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "Resolved"
  ): TypedContractEvent<
    ResolvedEvent.InputTuple,
    ResolvedEvent.OutputTuple,
    ResolvedEvent.OutputObject
  >;
  getEvent(
    key: "UsernameSet"
  ): TypedContractEvent<
    UsernameSetEvent.InputTuple,
    UsernameSetEvent.OutputTuple,
    UsernameSetEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "AvatarSet(address,string)": TypedContractEvent<
      AvatarSetEvent.InputTuple,
      AvatarSetEvent.OutputTuple,
      AvatarSetEvent.OutputObject
    >;
    AvatarSet: TypedContractEvent<
      AvatarSetEvent.InputTuple,
      AvatarSetEvent.OutputTuple,
      AvatarSetEvent.OutputObject
    >;

    "Cancelled(uint256)": TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;
    Cancelled: TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "GlobalPaused(bool)": TypedContractEvent<
      GlobalPausedEvent.InputTuple,
      GlobalPausedEvent.OutputTuple,
      GlobalPausedEvent.OutputObject
    >;
    GlobalPaused: TypedContractEvent<
      GlobalPausedEvent.InputTuple,
      GlobalPausedEvent.OutputTuple,
      GlobalPausedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MarketCreated(uint256,string,uint256,uint8)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Predicted(address,uint256,bool,uint256)": TypedContractEvent<
      PredictedEvent.InputTuple,
      PredictedEvent.OutputTuple,
      PredictedEvent.OutputObject
    >;
    Predicted: TypedContractEvent<
      PredictedEvent.InputTuple,
      PredictedEvent.OutputTuple,
      PredictedEvent.OutputObject
    >;

    "Refunded(address,uint256,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "Resolved(uint256,bool)": TypedContractEvent<
      ResolvedEvent.InputTuple,
      ResolvedEvent.OutputTuple,
      ResolvedEvent.OutputObject
    >;
    Resolved: TypedContractEvent<
      ResolvedEvent.InputTuple,
      ResolvedEvent.OutputTuple,
      ResolvedEvent.OutputObject
    >;

    "UsernameSet(address,string)": TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;
    UsernameSet: TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;

    "WinningsClaimed(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
