/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Greeter } from "./Greeter";
export type { MarketPredict } from "./MarketPredict";
export * as factories from "./factories";
export { Greeter__factory } from "./factories/Greeter__factory";
export { MarketPredict__factory } from "./factories/MarketPredict__factory";
