/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MarketPredictInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_FUTURE_TIME"
      | "MIN_PREDICTION"
      | "PLATFORM_FEE_BPS"
      | "PLATFORM_MAX_PER_MARKET"
      | "RESOLUTION_DELAY"
      | "VIRTUAL_LIQUIDITY"
      | "balances"
      | "calculatePotentialWinnings"
      | "calculateShares"
      | "claimRefund"
      | "claimWinnings"
      | "createMarket"
      | "deleteMarket"
      | "deposit"
      | "getBalance"
      | "getEffectiveLimit"
      | "getUserShares"
      | "getUserTotalInMarket"
      | "globalPaused"
      | "isRestricted"
      | "issueRefund"
      | "markets"
      | "nextMarketId"
      | "owner"
      | "pauseMarket"
      | "placePrediction"
      | "resolveMarket"
      | "restrictMyself"
      | "restrictedUntil"
      | "setMyMarketLimit"
      | "toggleGlobalPause"
      | "unpauseMarket"
      | "userMarketLimit"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "GlobalPauseToggled"
      | "MarketCreated"
      | "MarketDeleted"
      | "MarketPaused"
      | "MarketResolved"
      | "MarketUnpaused"
      | "PredictionPlaced"
      | "RefundIssued"
      | "UserLimitSet"
      | "UserRestricted"
      | "WinningsClaimed"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_FUTURE_TIME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PREDICTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_MAX_PER_MARKET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESOLUTION_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VIRTUAL_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePotentialWinnings",
    values: [BigNumberish, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateShares",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEffectiveLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserShares",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalInMarket",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRestricted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueRefund",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placePrediction",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictMyself",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictedUntil",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMyMarketLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleGlobalPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userMarketLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_FUTURE_TIME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PREDICTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_MAX_PER_MARKET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESOLUTION_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VIRTUAL_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePotentialWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalInMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placePrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictMyself",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictedUntil",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMyMarketLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleGlobalPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMarketLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPauseToggledEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    question: string,
    closeTime: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    question: string,
    closeTime: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    question: string;
    closeTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketDeletedEvent {
  export type InputTuple = [marketId: BigNumberish];
  export type OutputTuple = [marketId: bigint];
  export interface OutputObject {
    marketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketPausedEvent {
  export type InputTuple = [marketId: BigNumberish];
  export type OutputTuple = [marketId: bigint];
  export interface OutputObject {
    marketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [marketId: BigNumberish, outcomeYes: boolean];
  export type OutputTuple = [marketId: bigint, outcomeYes: boolean];
  export interface OutputObject {
    marketId: bigint;
    outcomeYes: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketUnpausedEvent {
  export type InputTuple = [marketId: BigNumberish];
  export type OutputTuple = [marketId: bigint];
  export interface OutputObject {
    marketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionPlacedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    side: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    side: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    side: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserLimitSetEvent {
  export type InputTuple = [user: AddressLike, limit: BigNumberish];
  export type OutputTuple = [user: string, limit: bigint];
  export interface OutputObject {
    user: string;
    limit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRestrictedEvent {
  export type InputTuple = [user: AddressLike, until: BigNumberish];
  export type OutputTuple = [user: string, until: bigint];
  export interface OutputObject {
    user: string;
    until: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarketPredict extends BaseContract {
  connect(runner?: ContractRunner | null): MarketPredict;
  waitForDeployment(): Promise<this>;

  interface: MarketPredictInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_FUTURE_TIME: TypedContractMethod<[], [bigint], "view">;

  MIN_PREDICTION: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_MAX_PER_MARKET: TypedContractMethod<[], [bigint], "view">;

  RESOLUTION_DELAY: TypedContractMethod<[], [bigint], "view">;

  VIRTUAL_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  calculatePotentialWinnings: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike, _side: boolean],
    [bigint],
    "view"
  >;

  calculateShares: TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [bigint],
    "view"
  >;

  claimRefund: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimWinnings: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [_question: string, _closeTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  deleteMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  getBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEffectiveLimit: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserShares: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [[bigint, bigint] & { yesShares: bigint; noShares: bigint }],
    "view"
  >;

  getUserTotalInMarket: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;

  globalPaused: TypedContractMethod<[], [boolean], "view">;

  isRestricted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  issueRefund: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [void],
    "nonpayable"
  >;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        question: string;
        yesPool: bigint;
        noPool: bigint;
        resolved: boolean;
        outcomeYes: boolean;
        closeTime: bigint;
        paused: boolean;
        deleted: boolean;
        totalYesShares: bigint;
        totalNoShares: bigint;
        totalYesAmount: bigint;
        totalNoAmount: bigint;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  placePrediction: TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveMarket: TypedContractMethod<
    [_marketId: BigNumberish, _outcomeYes: boolean],
    [void],
    "nonpayable"
  >;

  restrictMyself: TypedContractMethod<
    [duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  restrictedUntil: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setMyMarketLimit: TypedContractMethod<
    [limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  toggleGlobalPause: TypedContractMethod<[], [void], "nonpayable">;

  unpauseMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userMarketLimit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_FUTURE_TIME"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PREDICTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_MAX_PER_MARKET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESOLUTION_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VIRTUAL_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePotentialWinnings"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike, _side: boolean],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateShares"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [_question: string, _closeTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEffectiveLimit"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserShares"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [[bigint, bigint] & { yesShares: bigint; noShares: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTotalInMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRestricted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueRefund"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        question: string;
        yesPool: bigint;
        noPool: bigint;
        resolved: boolean;
        outcomeYes: boolean;
        closeTime: bigint;
        paused: boolean;
        deleted: boolean;
        totalYesShares: bigint;
        totalNoShares: bigint;
        totalYesAmount: bigint;
        totalNoAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "placePrediction"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _outcomeYes: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "restrictMyself"
  ): TypedContractMethod<[duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restrictedUntil"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMyMarketLimit"
  ): TypedContractMethod<[limit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleGlobalPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userMarketLimit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalPauseToggled"
  ): TypedContractEvent<
    GlobalPauseToggledEvent.InputTuple,
    GlobalPauseToggledEvent.OutputTuple,
    GlobalPauseToggledEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketDeleted"
  ): TypedContractEvent<
    MarketDeletedEvent.InputTuple,
    MarketDeletedEvent.OutputTuple,
    MarketDeletedEvent.OutputObject
  >;
  getEvent(
    key: "MarketPaused"
  ): TypedContractEvent<
    MarketPausedEvent.InputTuple,
    MarketPausedEvent.OutputTuple,
    MarketPausedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "MarketUnpaused"
  ): TypedContractEvent<
    MarketUnpausedEvent.InputTuple,
    MarketUnpausedEvent.OutputTuple,
    MarketUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionPlaced"
  ): TypedContractEvent<
    PredictionPlacedEvent.InputTuple,
    PredictionPlacedEvent.OutputTuple,
    PredictionPlacedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;
  getEvent(
    key: "UserLimitSet"
  ): TypedContractEvent<
    UserLimitSetEvent.InputTuple,
    UserLimitSetEvent.OutputTuple,
    UserLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "UserRestricted"
  ): TypedContractEvent<
    UserRestrictedEvent.InputTuple,
    UserRestrictedEvent.OutputTuple,
    UserRestrictedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "GlobalPauseToggled(bool)": TypedContractEvent<
      GlobalPauseToggledEvent.InputTuple,
      GlobalPauseToggledEvent.OutputTuple,
      GlobalPauseToggledEvent.OutputObject
    >;
    GlobalPauseToggled: TypedContractEvent<
      GlobalPauseToggledEvent.InputTuple,
      GlobalPauseToggledEvent.OutputTuple,
      GlobalPauseToggledEvent.OutputObject
    >;

    "MarketCreated(uint256,string,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketDeleted(uint256)": TypedContractEvent<
      MarketDeletedEvent.InputTuple,
      MarketDeletedEvent.OutputTuple,
      MarketDeletedEvent.OutputObject
    >;
    MarketDeleted: TypedContractEvent<
      MarketDeletedEvent.InputTuple,
      MarketDeletedEvent.OutputTuple,
      MarketDeletedEvent.OutputObject
    >;

    "MarketPaused(uint256)": TypedContractEvent<
      MarketPausedEvent.InputTuple,
      MarketPausedEvent.OutputTuple,
      MarketPausedEvent.OutputObject
    >;
    MarketPaused: TypedContractEvent<
      MarketPausedEvent.InputTuple,
      MarketPausedEvent.OutputTuple,
      MarketPausedEvent.OutputObject
    >;

    "MarketResolved(uint256,bool)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "MarketUnpaused(uint256)": TypedContractEvent<
      MarketUnpausedEvent.InputTuple,
      MarketUnpausedEvent.OutputTuple,
      MarketUnpausedEvent.OutputObject
    >;
    MarketUnpaused: TypedContractEvent<
      MarketUnpausedEvent.InputTuple,
      MarketUnpausedEvent.OutputTuple,
      MarketUnpausedEvent.OutputObject
    >;

    "PredictionPlaced(uint256,address,bool,uint256)": TypedContractEvent<
      PredictionPlacedEvent.InputTuple,
      PredictionPlacedEvent.OutputTuple,
      PredictionPlacedEvent.OutputObject
    >;
    PredictionPlaced: TypedContractEvent<
      PredictionPlacedEvent.InputTuple,
      PredictionPlacedEvent.OutputTuple,
      PredictionPlacedEvent.OutputObject
    >;

    "RefundIssued(uint256,address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;

    "UserLimitSet(address,uint256)": TypedContractEvent<
      UserLimitSetEvent.InputTuple,
      UserLimitSetEvent.OutputTuple,
      UserLimitSetEvent.OutputObject
    >;
    UserLimitSet: TypedContractEvent<
      UserLimitSetEvent.InputTuple,
      UserLimitSetEvent.OutputTuple,
      UserLimitSetEvent.OutputObject
    >;

    "UserRestricted(address,uint256)": TypedContractEvent<
      UserRestrictedEvent.InputTuple,
      UserRestrictedEvent.OutputTuple,
      UserRestrictedEvent.OutputObject
    >;
    UserRestricted: TypedContractEvent<
      UserRestrictedEvent.InputTuple,
      UserRestrictedEvent.OutputTuple,
      UserRestrictedEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
